// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkzxdvyjhljzvuydnbap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprenhkdnlqaGxqenZ1eWRuYmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NzQ1OTQsImV4cCI6MjA3NjQ1MDU5NH0.p0Z2wjP7t8_NiMfa5tATVyfVSf_VuLfQNMY0LSo-G-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});